USE FamishedBuffs;
INSERT INTO `Meal` (`HallID`, `Item`, `HourID`) VALUES
(01, 'Italian Sausage Pizza', 1),
(01, 'Cheese Pizza', 1),
(01, 'Pepperoni Pizza', 1),
(01, 'Gluten Free Pizza', 1),
(01, 'Peanut Butter and Jelly Sandwich', 1),
(01, 'Cheese Pizza', 2),
(01, 'Pepperoni Pizza', 2),
(01, 'Gluten Free Pizza', 2),
(01, 'Peanut Butter and Jelly Sandwich', 2),
(01, 'Cheese Pizza', 3),
(01, 'Pepperoni Pizza', 3),
(01, 'Gluten Free Pizza', 3),
(01, 'Peanut Butter and Jelly Sandwich', 3),
(01, 'Ham and Pineapple Pizza', 3),
(01, 'Cheese Pizza', 4),
(01, 'Pepperoni Pizza', 4),
(01, 'Gluten Free Pizza', 4),
(01, 'Peanut Butter and Jelly Sandwich', 4),
(01, 'Fresh Vegetable Pizza', 4),
(01, 'Cheese Pizza', 5),
(01, 'Pepperoni Pizza', 5),
(01, 'Gluten Free Pizza', 5),
(01, 'Peanut Butter and Jelly Sandwich', 5),
(20, 'Sandwich Bar', 57),
(20, 'Pasta with Meatballs or Italian Sausage', 57),
(20, 'Sandwich Bar', 58),
(20, 'Cheese Pizza', 58),
(20, 'Pepperoni Pizza', 58),
(20, 'Chicken Drummies and Rice', 58),
(20, 'Sandwich Bar', 59),
(20, 'Chicken Morsels and Rice', 59),
(20, 'Sandwich Bar', 60),
(20, 'Tacos', 60),
(20, 'Sandwich Bar', 61),
(20, 'Pulled Pork', 61);
