USE FamishedBuffs;
INSERT INTO 'DiningHalls' ('ID', 'Hall') VALUES
('FarG', 'Go Fresh @ Farrand Grab-n-Go'),
('Kitt', 'Kittredge Market'),
('SewM', 'Sewall Market'),
('VilM', 'Village Market'),
('VilG', 'Village Grab-n-Go'),
('FarM', 'Farrand Market'),
('SewD', 'Sewall'),
('C4CA', 'C4C Asian Shi Pin'),
('C4CB', 'C4C Black Coats'),
('C4CD', 'C4C Desserts'),
('C4CI', 'C4C Italian Cibo'),
('C4CK', 'C4C Kosher'),
('C4CL', 'C4C Latin Comida'),
('C4CP', 'C4C Persian Ghaza'),
('C4CM', 'C4C Smoke n Grill'),
('C4CS', 'C4C Sushi'),
('C4CR', 'C4C'),
('Libb', 'Libby'),
('WTec', 'Weathertech'),
('C4CG', 'CU on the Run Grab-n-Go'),
('Bakr', 'The Bakery'),
('SewG', 'Sewall Grab-n-Go');
