USE FamishedBuffs;
INSERT INTO `DiningHalls` (`Hall`, `Station`) VALUES
('Go Fresh @ Farrand Grab-n-Go', NULL),
('Kittredge Market', NULL),
('Sewall Market', NULL),
('Village Market', NULL),
('Village Grab-n-Go', NULL),
('Farrand Market', NULL),
('Sewall', NULL),
('C4C', 'Asian Shi Pin'),
('C4C', 'Black Coats'),
('C4C', 'Desserts'),
('C4C', 'Italian Cibo'),
('C4C', 'Kosher'),
('C4C', 'Latin Comida'),
('C4C', 'Persian Ghaza'),
('C4C', 'Smoke n Grill'),
('C4C', 'Sushi'),
('C4C', NULL),
('Libby', NULL),
('Weathertech', NULL),
('CU on the Run Grab-n-Go', NULL),
('The Bakery', NULL),
('Sewall Grab-n-Go', NULL);
