USE FamishedBuffs;
INSERT INTO `Meal` (`HallID`, `Day`, `Item`, `MealType`) VALUES
(18, 'Monday', "*Oatmeal", 'Breakfast'),
(18, 'Monday', "Omelet Bar", 'Breakfast'),
(18, 'Monday', "Scrambled Eggs", 'Breakfast'),
(18, 'Monday', "*Potato Triangles", 'Breakfast'),
(18, 'Monday', "Bacon", 'Breakfast'),
(18, 'Monday', "French Toast", 'Breakfast'),
(18, 'Monday', "Mazoh Brie", 'Breakfast'),
(18, 'Monday', "Assorted Doughnuts", 'Breakfast'),
(18, 'Monday', "Morning Harvest Muffins", 'Breakfast'),
(18, 'Monday', "White Chicken Chili", 'Lunch'),
(18, 'Monday', "Chipotle BBQ Pork Sandwich", 'Lunch'),
(18, 'Monday', "Swiss Cheese Penne Bake", 'Lunch'),
(18, 'Monday', "*Spicy BBQ Tempeh", 'Lunch'),
(18, 'Monday', "Battered Mushrooms", 'Lunch'),
(18, 'Monday', "*Steak Fries", 'Lunch'),
(18, 'Monday', "*Green Peas", 'Lunch'),
(18, 'Monday', "*Deli Bar", 'Lunch'),
(18, 'Monday', "Chocolate Chunk Cookies", 'Lunch'),
(18, 'Monday', "White Chocolate Craisin Blondie", 'Lunch'),
(18, 'Monday', "Soup du Jour", 'Dinner'),
(18, 'Monday', "Mandarin Orange Chicken", 'Dinner'),
(18, 'Monday', "Salmon with Teriyaki Ginger Glaze", 'Dinner'),
(18, 'Monday', "*Broccoli Tofu with Garlic Sauce", 'Dinner'),
(18, 'Monday', "*Steamed Brown Rice", 'Dinner'),
(18, 'Monday', "*Garden Vegetable Medley", 'Dinner'),
(18, 'Monday', "*Deli Bar", 'Dinner'),
(18, 'Monday', "Dinner Rolls", 'Dinner'),
(18, 'Monday', "Wild Berry Pie with Lemon Crust", 'Dinner'),
(18, 'Monday', "Red Velvet Cake with Cream Cheese Icing", 'Dinner'),
(18, 'Tuesday', "*Oatmeal", 'Breakfast'),
(18, 'Tuesday', "Omelet Bar", 'Breakfast'),
(18, 'Tuesday', "Scrambled Eggs", 'Breakfast'),
(18, 'Tuesday', "*Tofu Scramble", 'Breakfast'),
(18, 'Tuesday', "*Hashbrowns", 'Breakfast'),
(18, 'Tuesday', "Maple Sausage", 'Breakfast'),
(18, 'Tuesday', "Buttermilk Pancakes", 'Breakfast'),
(18, 'Tuesday', "Mazoh Brie", 'Breakfast'),
(18, 'Tuesday', "Muffins du Jour", 'Breakfast'),
(18, 'Tuesday', "Cinnamon Rolls", 'Breakfast'),
(18, 'Tuesday', "*Vegetable Soup", 'Lunch'),
(18, 'Tuesday', "Grilled Philly Steak Sandwich", 'Lunch'),
(18, 'Tuesday', "Crab Cakes with Cilantro Lime Aioli", 'Lunch'),
(18, 'Tuesday', "*Ginger Vegetable Stir Fry", 'Lunch'),
(18, 'Tuesday', "*French Fries", 'Lunch'),
(18, 'Tuesday', "*Deli Bar", 'Lunch'),
(18, 'Tuesday', "Peanut Butter Cup Cookies", 'Lunch'),
(18, 'Tuesday', "Kiwi Biscuits", 'Lunch'),
(18, 'Tuesday', "Soup du Jour", 'Dinner'),
(18, 'Tuesday', "Italian Lasagna - Meat or Cheese", 'Dinner'),
(18, 'Tuesday', "Battered Green Beans with Spicy Peach BBQ Sauce", 'Dinner'),
(18, 'Tuesday', "*Grilled Zucchini with Kalamata Olive Spread", 'Dinner'),
(18, 'Tuesday', "*Gluten Free Rotini", 'Dinner'),
(18, 'Tuesday', "*Marinara Sauce", 'Dinner'),
(18, 'Tuesday', "*Italian Blend Vegetables", 'Dinner'),
(18, 'Tuesday', "*Deli Bar", 'Dinner'),
(18, 'Tuesday', "Bread Sticks", 'Dinner'),
(18, 'Tuesday', "Nutella Cheesecake", 'Dinner'),
(18, 'Tuesday', "Coconut Cream Pie", 'Dinner'),
(18, 'Wednesday', "*Oatmeal", 'Breakfast'),
(18, 'Wednesday', "Omelet Bar", 'Breakfast'),
(18, 'Wednesday', "Scrambled Eggs", 'Breakfast'),
(18, 'Wednesday', "*Tofu Scramble", 'Breakfast'),
(18, 'Wednesday', "Home Fries", 'Breakfast'),
(18, 'Wednesday', "Baked Ham Slices", 'Breakfast'),
(18, 'Wednesday', "Banana French Toast", 'Breakfast'),
(18, 'Wednesday', "Mazoh Brie", 'Breakfast'),
(18, 'Wednesday', "Chocolate Mini Croissants", 'Breakfast'),
(18, 'Wednesday', "Strawberry Coffee Cake", 'Breakfast'),
(18, 'Wednesday', "Curry Coconut Chicken Soup", 'Lunch'),
(18, 'Wednesday', "Ham and Swiss Sandwich on Sourdough Bread", 'Lunch'),
(18, 'Wednesday', "Spicy Cheese Pupusas with Curtido", 'Lunch'),
(18, 'Wednesday', "Chef's Choice Fish Entree", 'Lunch'),
(18, 'Wednesday', "*Fresh Vegetable Pasta Primavera", 'Lunch'),
(18, 'Wednesday', "*Winter Blend Vegetables", 'Lunch'),
(18, 'Wednesday', "*Deli Bar", 'Lunch'),
(18, 'Wednesday', "Oatmeal Raisin Cookies", 'Lunch'),
(18, 'Wednesday', "Banana Bars", 'Lunch'),
(18, 'Wednesday', "Soup du Jour", 'Dinner'),
(18, 'Wednesday', "Grilled Chicken Breast with Spinach and Chipotle Cream", 'Dinner'),
(18, 'Wednesday', "Chef's Choice Entree", 'Dinner'),
(18, 'Wednesday', "*Sweet and Sour Tofu", 'Dinner'),
(18, 'Wednesday', "*Wild Rice Pilaf", 'Dinner'),
(18, 'Wednesday', "*Francais Blend Vegetables", 'Dinner'),
(18, 'Wednesday', "*Deli Bar", 'Dinner'),
(18, 'Wednesday', "Cornbread with Honey Butter", 'Dinner'),
(18, 'Wednesday', "Lemon Poppy Cake", 'Dinner'),
(18, 'Wednesday', "*Cherry Pie", 'Dinner'),
(18, 'Thursday', "*Oatmeal", 'Breakfast'),
(18, 'Thursday', "Omelet Bar", 'Breakfast'),
(18, 'Thursday', "Scrambled Eggs", 'Breakfast'),
(18, 'Thursday', "*Tofu Scramble", 'Breakfast'),
(18, 'Thursday', "*Hashbrowns", 'Breakfast'),
(18, 'Thursday', "Bacon", 'Breakfast'),
(18, 'Thursday', "Biscuits and Sausage Gravy", 'Breakfast'),
(18, 'Thursday', "Blueberry Pancakes", 'Breakfast'),
(18, 'Thursday', "Mazoh Brie", 'Breakfast'),
(18, 'Thursday', "Caramel Twists", 'Breakfast'),
(18, 'Thursday', "Blueberry Muffins", 'Breakfast'),
(18, 'Thursday', "*Carrot Ginger Soup", 'Lunch'),
(18, 'Thursday', "BBQ Beef Sandwich", 'Lunch'),
(18, 'Thursday', "Chicken Nuggets", 'Lunch'),
(18, 'Thursday', "*Frito Pie", 'Lunch'),
(18, 'Thursday', "Sweet Potato Galette", 'Lunch'),
(18, 'Thursday', "Mashed Potatoes and Gravy", 'Lunch'),
(18, 'Thursday', "*Broccoli Florets", 'Lunch'),
(18, 'Thursday', "*Deli Bar", 'Lunch'),
(18, 'Thursday', "M&M Cookies", 'Lunch'),
(18, 'Thursday', "Chocolate Chip Cookies", 'Lunch'),
(18, 'Thursday', "Soup du Jour", 'Dinner'),
(18, 'Thursday', "Ginger Garlic Pork Tenderloin", 'Dinner'),
(18, 'Thursday', "Cheese Stuffed Shells", 'Dinner'),
(18, 'Thursday', "*Gluten Free Rotini", 'Dinner'),
(18, 'Thursday', "*Marinara Sauce", 'Dinner'),
(18, 'Thursday', "*Tempeh over Roasted Vegetables", 'Dinner'),
(18, 'Thursday', "*Baby Carrots", 'Dinner'),
(18, 'Thursday', "*Sugar Snap Peas", 'Dinner'),
(18, 'Thursday', "*Deli Bar", 'Dinner'),
(18, 'Thursday', "Parkerhouse Rolls", 'Dinner'),
(18, 'Thursday', "German Chocolate Nut Cake", 'Dinner'),
(18, 'Thursday', "Caramel Apple Streusel Cobbler", 'Dinner'),
(18, 'Friday', "*Oatmeal", 'Breakfast'),
(18, 'Friday', "Omelet Bar", 'Breakfast'),
(18, 'Friday', "Scrambled Eggs", 'Breakfast'),
(18, 'Friday', "*Tofu Scramble", 'Breakfast'),
(18, 'Friday', "*Potato Triangles", 'Breakfast'),
(18, 'Friday', "Sausage Patties", 'Breakfast'),
(18, 'Friday', "French Toast", 'Breakfast'),
(18, 'Friday', "Mazoh Brie", 'Breakfast'),
(18, 'Friday', "Chocolate Chip Scone", 'Breakfast'),
(18, 'Friday', "Cream Cheese Coffee Cake", 'Breakfast'),
(18, 'Friday', "Chicken Tortilla Soup", 'Lunch'),
(18, 'Friday', "Build-Your-Own Burrito Bar - Seasoned Beef or *Seitan", 'Lunch'),
(18, 'Friday', "Baked Ruby Red Trout with Tomatillo Salsa", 'Lunch'),
(18, 'Friday', "*Green Chili", 'Lunch'),
(18, 'Friday', "*Refried Beans", 'Lunch'),
(18, 'Friday', "Pork Tamales", 'Lunch'),
(18, 'Friday', "*Cilantro Lime Rice", 'Lunch'),
(18, 'Friday', "*Mixed Vegetables", 'Lunch'),
(18, 'Friday', "Nacho Chips", 'Lunch'),
(18, 'Friday', "*Deli Bar", 'Lunch'),
(18, 'Friday', "Double Chocolate Chunk Cookies", 'Lunch'),
(18, 'Friday', "Oatmeal Fruit Bars", 'Lunch'),
(18, 'Friday', "No Meal Served", 'Dinner'),
(18, 'Friday', "No Meal Served", 'Lunch'),
(18, 'Friday', "No Meal Served", 'Dinner'),
(18, 'Friday', "No Meal Served", 'Lunch'),
(18, 'Friday', "No Meal Served", 'Dinner'),
(07, 'Monday', "*Oatmeal", 'Breakfast'),
(07, 'Monday', "Omelet Bar", 'Breakfast'),
(07, 'Monday', "Scrambled Eggs", 'Breakfast'),
(07, 'Monday', "*Potato Triangles", 'Breakfast'),
(07, 'Monday', "Bacon", 'Breakfast'),
(07, 'Monday', "French Toast", 'Breakfast'),
(07, 'Monday', "Build-Your-Own Waffles", 'Breakfast'),
(07, 'Monday', "Assorted Doughnuts", 'Breakfast'),
(07, 'Monday', "Morning Harvest Muffins", 'Breakfast'),
(07, 'Monday', "White Chicken Chili", 'Lunch'),
(07, 'Monday', "Chipotle BBQ Pork Sandwich", 'Lunch'),
(07, 'Monday', "Swiss Cheese Penne Bake", 'Lunch'),
(07, 'Monday', "*Spicy BBQ Tempeh", 'Lunch'),
(07, 'Monday', "Battered Mushrooms", 'Lunch'),
(07, 'Monday', "*Steak Fries", 'Lunch'),
(07, 'Monday', "*Green Peas", 'Lunch'),
(07, 'Monday', "*Deli Bar", 'Lunch'),
(07, 'Monday', "Chocolate Chunk Cookies", 'Lunch'),
(07, 'Monday', "White Chocolate Craisin Blondie", 'Lunch'),
(07, 'Monday', "Soup du Jour", 'Dinner'),
(07, 'Monday', "Mandarin Orange Chicken", 'Dinner'),
(07, 'Monday', "Salmon with Teriyaki Ginger Glaze", 'Dinner'),
(07, 'Monday', "*Broccoli Tofu with Garlic Sauce", 'Dinner'),
(07, 'Monday', "*Steamed Brown Rice", 'Dinner'),
(07, 'Monday', "*Garden Vegetable Medley", 'Dinner'),
(07, 'Monday', "*Deli Bar", 'Dinner'),
(07, 'Monday', "Dinner Rolls", 'Dinner'),
(07, 'Monday', "Wild Berry Pie with Lemon Crust", 'Dinner'),
(07, 'Monday', "Red Velvet Cake with Cream Cheese Icing", 'Dinner'),
(07, 'Tuesday', "*Oatmeal", 'Breakfast'),
(07, 'Tuesday', "Omelet Bar", 'Breakfast'),
(07, 'Tuesday', "Scrambled Eggs", 'Breakfast'),
(07, 'Tuesday', "*Tofu Scramble", 'Breakfast'),
(07, 'Tuesday', "*Hashbrowns", 'Breakfast'),
(07, 'Tuesday', "Maple Sausage", 'Breakfast'),
(07, 'Tuesday', "Buttermilk Pancakes", 'Breakfast'),
(07, 'Tuesday', "Build-Your-Own Waffles", 'Breakfast'),
(07, 'Tuesday', "Muffins du Jour", 'Breakfast'),
(07, 'Tuesday', "Cinnamon Rolls", 'Breakfast'),
(07, 'Tuesday', "*Vegetable Soup", 'Lunch'),
(07, 'Tuesday', "Grilled Philly Steak Sandwich", 'Lunch'),
(07, 'Tuesday', "Crab Cakes with Cilantro Lime Aioli", 'Lunch'),
(07, 'Tuesday', "*Ginger Vegetable Stir Fry", 'Lunch'),
(07, 'Tuesday', "*French Fries", 'Lunch'),
(07, 'Tuesday', "*Deli Bar", 'Lunch'),
(07, 'Tuesday', "Peanut Butter Cup Cookies", 'Lunch'),
(07, 'Tuesday', "Kiwi Biscuits", 'Lunch'),
(07, 'Tuesday', "Soup du Jour", 'Dinner'),
(07, 'Tuesday', "Italian Lasagna - Meat or Cheese", 'Dinner'),
(07, 'Tuesday', "Battered Green Beans with Spicy Peach BBQ Sauce", 'Dinner'),
(07, 'Tuesday', "*Grilled Zucchini with Kalamata Olive Spread", 'Dinner'),
(07, 'Tuesday', "*Gluten Free Rotini", 'Dinner'),
(07, 'Tuesday', "*Marinara Sauce", 'Dinner'),
(07, 'Tuesday', "*Italian Blend Vegetables", 'Dinner'),
(07, 'Tuesday', "*Deli Bar", 'Dinner'),
(07, 'Tuesday', "Bread Sticks", 'Dinner'),
(07, 'Tuesday', "Nutella Cheesecake", 'Dinner'),
(07, 'Tuesday', "Coconut Cream Pie", 'Dinner'),
(07, 'Wednesday', "*Oatmeal", 'Breakfast'),
(07, 'Wednesday', "Omelet Bar", 'Breakfast'),
(07, 'Wednesday', "Scrambled Eggs", 'Breakfast'),
(07, 'Wednesday', "*Tofu Scramble", 'Breakfast'),
(07, 'Wednesday', "Home Fries", 'Breakfast'),
(07, 'Wednesday', "Baked Ham Slices", 'Breakfast'),
(07, 'Wednesday', "Banana French Toast", 'Breakfast'),
(07, 'Wednesday', "Build-Your-Own Waffles", 'Breakfast'),
(07, 'Wednesday', "Chocolate Mini Croissants", 'Breakfast'),
(07, 'Wednesday', "Strawberry Coffee Cake", 'Breakfast'),
(07, 'Wednesday', "Curry Coconut Chicken Soup", 'Lunch'),
(07, 'Wednesday', "Ham and Swiss Sandwich on Sourdough Bread", 'Lunch'),
(07, 'Wednesday', "Spicy Cheese Pupusas with Curtido", 'Lunch'),
(07, 'Wednesday', "Chef's Choice Fish Entree", 'Lunch'),
(07, 'Wednesday', "*Fresh Vegetable Pasta Primavera", 'Lunch'),
(07, 'Wednesday', "*Winter Blend Vegetables", 'Lunch'),
(07, 'Wednesday', "*Deli Bar", 'Lunch'),
(07, 'Wednesday', "Oatmeal Raisin Cookies", 'Lunch'),
(07, 'Wednesday', "Banana Bars", 'Lunch'),
(07, 'Wednesday', "Soup du Jour", 'Dinner'),
(07, 'Wednesday', "Grilled Chicken Breast with Spinach and Chipotle Cream", 'Dinner'),
(07, 'Wednesday', "Chef's Choice Entree", 'Dinner'),
(07, 'Wednesday', "*Sweet and Sour Tofu", 'Dinner'),
(07, 'Wednesday', "*Wild Rice Pilaf", 'Dinner'),
(07, 'Wednesday', "*Francais Blend Vegetables", 'Dinner'),
(07, 'Wednesday', "*Deli Bar", 'Dinner'),
(07, 'Wednesday', "Cornbread with Honey Butter", 'Dinner'),
(07, 'Wednesday', "Lemon Poppy Cake", 'Dinner'),
(07, 'Wednesday', "*Cherry Pie", 'Dinner'),
(07, 'Thursday', "*Oatmeal", 'Breakfast'),
(07, 'Thursday', "Omelet Bar", 'Breakfast'),
(07, 'Thursday', "Scrambled Eggs", 'Breakfast'),
(07, 'Thursday', "*Tofu Scramble", 'Breakfast'),
(07, 'Thursday', "*Hashbrowns", 'Breakfast'),
(07, 'Thursday', "Bacon", 'Breakfast'),
(07, 'Thursday', "Biscuits and Sausage Gravy", 'Breakfast'),
(07, 'Thursday', "Blueberry Pancakes", 'Breakfast'),
(07, 'Thursday', "Build-Your-Own Waffles", 'Breakfast'),
(07, 'Thursday', "Caramel Twists", 'Breakfast'),
(07, 'Thursday', "Blueberry Muffins", 'Breakfast'),
(07, 'Thursday', "*Carrot Ginger Soup", 'Lunch'),
(07, 'Thursday', "BBQ Beef Sandwich", 'Lunch'),
(07, 'Thursday', "Chicken Nuggets", 'Lunch'),
(07, 'Thursday', "*Frito Pie", 'Lunch'),
(07, 'Thursday', "Sweet Potato Galette", 'Lunch'),
(07, 'Thursday', "Mashed Potatoes and Gravy", 'Lunch'),
(07, 'Thursday', "*Broccoli Florets", 'Lunch'),
(07, 'Thursday', "*Deli Bar", 'Lunch'),
(07, 'Thursday', "M&M Cookies", 'Lunch'),
(07, 'Thursday', "Chocolate Chip Cookies", 'Lunch'),
(07, 'Thursday', "Soup du Jour", 'Dinner'),
(07, 'Thursday', "Ginger Garlic Pork Tenderloin", 'Dinner'),
(07, 'Thursday', "Cheese Stuffed Shells", 'Dinner'),
(07, 'Thursday', "*Gluten Free Rotini", 'Dinner'),
(07, 'Thursday', "*Marinara Sauce", 'Dinner'),
(07, 'Thursday', "*Tempeh over Roasted Vegetables", 'Dinner'),
(07, 'Thursday', "*Baby Carrots", 'Dinner'),
(07, 'Thursday', "*Sugar Snap Peas", 'Dinner'),
(07, 'Thursday', "*Deli Bar", 'Dinner'),
(07, 'Thursday', "Parkerhouse Rolls", 'Dinner'),
(07, 'Thursday', "German Chocolate Nut Cake", 'Dinner'),
(07, 'Thursday', "Caramel Apple Streusel Cobbler", 'Dinner'),
(07, 'Friday', "*Oatmeal", 'Breakfast'),
(07, 'Friday', "Omelet Bar", 'Breakfast'),
(07, 'Friday', "Scrambled Eggs", 'Breakfast'),
(07, 'Friday', "*Tofu Scramble", 'Breakfast'),
(07, 'Friday', "*Potato Triangles", 'Breakfast'),
(07, 'Friday', "Sausage Patties", 'Breakfast'),
(07, 'Friday', "French Toast", 'Breakfast'),
(07, 'Friday', "Build-Your-Own Waffles", 'Breakfast'),
(07, 'Friday', "Chocolate Chip Scone", 'Breakfast'),
(07, 'Friday', "Cream Cheese Coffee Cake", 'Breakfast'),
(07, 'Friday', "Chicken Tortilla Soup", 'Lunch'),
(07, 'Friday', "Build-Your-Own Burrito Bar - Seasoned Beef or *Seitan", 'Lunch'),
(07, 'Friday', "Baked Ruby Red Trout with Tomatillo Salsa", 'Lunch'),
(07, 'Friday', "*Green Chili", 'Lunch'),
(07, 'Friday', "*Refried Beans", 'Lunch'),
(07, 'Friday', "Pork Tamales", 'Lunch'),
(07, 'Friday', "*Cilantro Lime Rice", 'Lunch'),
(07, 'Friday', "*Mixed Vegetables", 'Lunch'),
(07, 'Friday', "Nacho Chips", 'Lunch'),
(07, 'Friday', "*Deli Bar", 'Lunch'),
(07, 'Friday', "Double Chocolate Chunk Cookies", 'Lunch'),
(07, 'Friday', "Oatmeal Fruit Bars", 'Lunch'),
(07, 'Friday', "Soup du Jour", 'Dinner'),
(07, 'Friday', "Southwestern Petite Tender of Beef with Bleu Cheese Beer Sauce", 'Dinner'),
(07, 'Friday', "Hawaiian Macadamia Pesto Tilapia", 'Dinner'),
(07, 'Friday', "*Ratatouille", 'Dinner'),
(07, 'Friday', "*Baked Potatoes", 'Dinner'),
(07, 'Friday', "*Steamed Rice", 'Dinner'),
(07, 'Friday', "*Deli Bar", 'Dinner'),
(07, 'Friday', "Dinner Rolls", 'Dinner'),
(07, 'Friday', "Banana Cream Pie", 'Dinner'),
(07, 'Saturday', "*Oatmeal", 'Lunch'),
(07, 'Saturday', "Chicken Gumbo Soup", 'Lunch'),
(07, 'Saturday', "Mushroom Pepper Scramblettes", 'Lunch'),
(07, 'Saturday', "Scrambled Eggs", 'Lunch'),
(07, 'Saturday', "*Tofu Scramble", 'Lunch'),
(07, 'Saturday', "Chicken Stir Fry", 'Lunch'),
(07, 'Saturday', "*Teriyaki Tofu", 'Lunch'),
(07, 'Saturday', "*Vegetable Potstickers", 'Lunch'),
(07, 'Saturday', "*Steamed Rice", 'Lunch'),
(07, 'Saturday', "Sausage Links", 'Lunch'),
(07, 'Saturday', "*Tater Tots", 'Lunch'),
(07, 'Saturday', "*Seasoned Baby Spinach", 'Lunch'),
(07, 'Saturday', "*Deli Bar", 'Lunch'),
(07, 'Saturday', "Build-Your-Own Waffles", 'Lunch'),
(07, 'Saturday', "Breakfast Pastry Bar", 'Lunch'),
(07, 'Saturday', "Soup & Sandwich Bar:", 'Dinner'),
(07, 'Saturday', "*Tomato Soup", 'Dinner'),
(07, 'Saturday', "Grilled Cheese Sandwich", 'Dinner'),
(07, 'Saturday', "Build-Your-Own BLT", 'Dinner'),
(07, 'Saturday', "Ha", 'Dinner'),
(07, 'Saturday', "Chili", 'Dinner'),
(07, 'Saturday', "*Vegetarian Chili", 'Dinner'),
(07, 'Saturday', "Tuna Melt Bake", 'Dinner'),
(07, 'Saturday', "Waffle Fries", 'Dinner'),
(07, 'Saturday', "*Green Beans", 'Dinner'),
(07, 'Saturday', "*Deli Bar", 'Dinner'),
(07, 'Saturday', "Dutch Apple Pie", 'Dinner'),
(07, 'Sunday', "*Oatmeal", 'Lunch'),
(07, 'Sunday', "*Three Bean Chili", 'Lunch'),
(07, 'Sunday', "Omelet Bar", 'Lunch'),
(07, 'Sunday', "Scrambled Eggs", 'Lunch'),
(07, 'Sunday', "Bacon", 'Lunch'),
(07, 'Sunday', "Chef's Choice Entree", 'Lunch'),
(07, 'Sunday', "Croissant Sandwiches - Ham and Swiss or Spinach and Feta", 'Lunch'),
(07, 'Sunday', "*Tofu Rancheros", 'Lunch'),
(07, 'Sunday', "*Potato Pancakes", 'Lunch'),
(07, 'Sunday', "*Key Largo Blend Vegetables", 'Lunch'),
(07, 'Sunday', "*Deli Bar", 'Lunch'),
(07, 'Sunday', "Build-Your-Own Waffles", 'Lunch'),
(07, 'Sunday', "Breakfast Pastry Bar", 'Lunch'),
(07, 'Sunday', "Italian Wedding Soup", 'Dinner'),
(07, 'Sunday', "Chicken Parmesan", 'Dinner'),
(07, 'Sunday', "Blackened Catfish", 'Dinner'),
(07, 'Sunday', "*Colorado Tofu", 'Dinner'),
(07, 'Sunday', "*Spaghetti", 'Dinner'),
(07, 'Sunday', "*Gluten Free Rotini", 'Dinner'),
(07, 'Sunday', "*Marinara Sauce", 'Dinner'),
(07, 'Sunday', "*Baked Acorn Squash", 'Dinner'),
(07, 'Sunday', "*Deli Bar", 'Dinner'),
(07, 'Sunday', "Garlic Bread", 'Dinner'),
(07, 'Sunday', "M&M Brownies", 'Dinner'),
(07, 'Sunday', "Ice Cream Sundae Bar", 'Dinner')  ;